name: grafana 
version: 2.1.3-1
vendor: Woodrow Shen <woodrow.shen@canonical.com>
summary: Graphite and InfluxDB Dashboard and graph builder
description: The graphite dashboard frontend and editor and graph composer
icon: icon.png
architectures: [armhf]
services:
  grafana:
    start: bin/start-service.sh
    ports:
      external:
          ui:
            port: 3000/tcp
            negotiable: no
    security-override:
      apparmor: etc/grafana.apparmor
      seccomp: etc/grafana.seccomp
parts:
  grafana:
    plugin: make 
    source: . 

