name: grafana 
version: 2.6.0-1
vendor: Woodrow Shen <woodrow.shen@canonical.com>
summary: Graphite and InfluxDB Dashboard and graph builder
description: The graphite dashboard frontend and editor and graph composer
icon: icon.png
services:
  grafana:
    start: bin/start-service.sh
    description: grafana service
    ports:
      external:
          ui:
            port: 3000/tcp
            negotiable: no
    security-override:
      apparmor: meta/grafana.apparmor
      seccomp: meta/grafana.seccomp
parts:
  grafana:
    plugin: make 
    source: . 

