name: grafana 
version: 2.6.0-2
summary: Graphite and InfluxDB Dashboard and graph builder
description: The graphite dashboard frontend and editor and graph composer
confinement: strict
grade: stable

apps:
  grafana:
    command: bin/grafana-internal
    plugs:
      - network
      - network-bind
    daemon: simple

parts:
  grafana-common:
    plugin: dump
    source: bin
    organize:
      grafana-internal: bin/
  grafana:
    plugin: nil
    source-type: git
    source: https://github.com/grafana/grafana
    prepare: |
      mkdir -p $GOPATH/src/github.com/grafana
      ln -s  $PWD $GOPATH/src/github.com/grafana/grafana
    build: |
      cd $GOPATH/src/github.com/grafana/grafana
      go run build.go setup
      go run build.go build
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/conf
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp conf/defaults.ini $SNAPCRAFT_PART_INSTALL/conf/
      cp bin/* $SNAPCRAFT_PART_INSTALL/bin/
    after: [go]
  go:
    source-tag: go1.8.3
  grafana-ui:
    plugin: nil
    source-type: git
    source: https://github.com/grafana/grafana
    prepare: |
      mkdir ~/.npm-global
      npm config set prefix '~/.npm-global'
      export PATH=~/.npm-global/bin:$PATH
    build: |
      npm install -g yarn
      yarn install --pure-lockfile
      npm run build
    install: |
      cp -rf public_gen $SNAPCRAFT_PART_INSTALL/public
    after: [grafana]
